### PR TITLE
Batch augmentor

### PR DESCRIPTION
**Pull request by EthanMarx**
Implements new batch augmentor that allows incorporation of SNR curriculum learning (currently just a dummy step that does nothing).

### CODE REVIEW

**Comment by wbenoit26** [comment]
This looks pretty nice to me, other than the extraneous notebook. I lost track of the status of your `SnrRescaler` PR in `ml4gw` - is that more or less good to go, and would you prefer to get that merged in and use that here?

**Comment by EthanMarx** [comment]
There will never not be an extraneous notebook from me. 

The `SnrRescaler` PR is coupled with other changes that I'm now not really a huge fan of. I do think the `SnrRescaler` itself is a sufficiently general / useful tool, so maybe we merge that in by itself in a separate PR. 

Still need some unit tests here too

**Comment by wbenoit26** [comment]
Ah, I remember now, yeah. I think integrating the `SnrRescaler` in a separate PR makes sense, as long as there aren't any issues building it into `RandomWaveformInjection`.

Yeah, for sure.

**Comment by EthanMarx** [comment]
I think the idea was the break up / remove `RandomWaveformInjection`. After this PR we won't actually use it in `aframe` (almost said BBHNet there ). The `SnrRescaler` factors out a large component of it (the `.fit` method). I'm not completely sure what else is worth generalizing. Maybe the `sample_responses` function that I have in the `BatchAugmentor`?

**Comment by wbenoit26** [comment]
Isn't that what `waveforms.py` takes care of in your `ml4gw` PR? Are those the other changes that you're not a fan of?

**Comment by EthanMarx** [comment]
Yeah exactly. I'm thinking it might be best to combine the `Sampler` and `Projector`.

**Comment by wbenoit26** [comment]
That seems good to me, maybe with a flag to determine whether calling it returns the raw waveforms or the projected ones

**Comment by EthanMarx** [comment]
I think I would rather keep them separate actually than introduce a flag. Ahh I keep going back and forth.

**Pull request closed without merging**
