### PR TITLE
Chunked glitch loader

### PR DESCRIPTION
**Pull request by EthanMarx**
Rebased version of #367

### CODE REVIEW

**Comment by EthanMarx** [comment]
@wbenoit26 I really botched the rebase of #367 so made this new PR.

**Comment by wbenoit26** [comment]
Hah, I see, thanks for dealing with that.

**Comment by alecgunny** [comment]
Oh wait shoot I didn't realize that deleting `mdc-dev` would close this, but I guess that makes sense. Can you reopen it against `main`?

**Comment by EthanMarx** [comment]
Oooh I see. Yeah can do

**Pull request closed without merging**
