### PR TITLE
Cleaning up docstrings and variable names

### PR DESCRIPTION
**Pull request by wbenoit26**
Starting to get organized around making sure docstrings are accurate and complete (at least for the main functions), and that we're relatively consistent and not confusing with our variable names. Obviously, this will need to be modified as more updates come in, but I think a lot of these changes can be made independent of what's going on elsewhere.

Docstrings:
- [x] Datagen
- [ ] Training
- [x] Export
- [ ] Inference
- [ ] VizApp
- [ ] Analysis
- [ ] Architectures
- [ ] Deploy
- [x] Logging
- [x] Priors
- [ ] Trainer

Variable Name Cleanup:
- [ ] Literally everything

### CODE REVIEW

**Comment by EthanMarx** [comment]
I might suggest doing this in multiple, shorter PRs such that it doesn't get severely behind `main`. Up to you, but happy to help reviewing / getting these in quickly

**Comment by wbenoit26** [comment]
I think I can hammer out the docstrings pretty quick, even if I end up needing to redo a couple, but you're right, aligning variable names will take a while. I'll split this into a couple PRs.

**Comment by wbenoit26** [comment]
Or, actually, let me ask: what level of function/class do we want to have docstrings for prior to publicizing our code? I was thinking of just having it for the main, front-facing code, but I could see the argument that we want everything to at least have a description. In the latter case, I totally agree, this should be done over multiple PRs.

Tagging @alecgunny in case he has opinions as well.

**Comment by wbenoit26** [comment]
Closing to split into multiple

**Pull request closed without merging**
